In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"C:\Users\thoma\Downloads\imdb(MOVIES).csv")
df

ranking of movie                   movie name    Year certificate  \
0                   1                      Jai Bhim  -2021       TV-MA   
1                   2      The Shawshank Redemption  -1994           R   
2                   3                 The Godfather  -1972           R   
3                   4               The Dark Knight  -2008       PG-13   
4                   5        The Godfather: Part II  -1974           R   
..                ...                           ...    ...         ...   
245               246  Mr. Smith Goes to Washington  -1939      Passed   
246               247            Gone with the Wind  -1939      Passed   
247               248         It Happened One Night  -1934      Passed   
248               249    The Passion of Joan of Arc  -1928      Passed   
249               250                   The General  -1926      Passed   

     runtime                      genre  RATING  \
0    164 min               Crime, Drama     9.4   
1    142 min                      Drama     9.3   
2    175 min               Crime, Drama     9.2   
3    152 min       Action, Crime, Drama     9.0   
4    202 min               Crime, Drama     9.0   
..       ...                        ...     ...   
245  129 min              Comedy, Drama     8.1   
246  238 min    Drama, History, Romance     8.1   
247  105 min            Comedy, Romance     8.1   
248  114 min  Biography, Drama, History     8.1   
249   67 min  Action, Adventure, Comedy     8.1   

                                    DETAIL ABOUT MOVIE             DIRECTOR   \
0    When a tribal man is arrested for a case of al...         T.J. Gnanavel   
1    Two imprisoned men bond over a number of years...        Frank Darabont   
2    The Godfather follows Vito Corleone, Don of th...  Francis Ford Coppola   
3    When the menace known as the Joker wreaks havo...     Christopher Nolan   
4    The early life and career of Vito Corleone in ...  Francis Ford Coppola   
..                                                 ...                   ...   
245  A naive youth leader is appointed to fill a va...           Frank Capra   
246  The manipulative daughter of a Georgia plantat...        Victor Fleming   
247  A renegade reporter trailing a young runaway h...           Frank Capra   
248  In 1431, Jeanne d'Arc is placed on trial on ch...   Carl Theodor Dreyer   
249  After being rejected by the Confederate milita...        Clyde Bruckman   

              ACTOR 1            ACTOR 2          ACTOR 3          ACTOR 4  \
0              Suriya      Lijo Mol Jose       Manikandan  Rajisha Vijayan   
1         Tim Robbins     Morgan Freeman       Bob Gunton   William Sadler   
2       Marlon Brando          Al Pacino       James Caan     Diane Keaton   
3      Christian Bale       Heath Ledger    Aaron Eckhart    Michael Caine   
4           Al Pacino     Robert De Niro    Robert Duvall     Diane Keaton   
..                ...                ...              ...              ...   
245     James Stewart        Jean Arthur     Claude Rains    Edward Arnold   
246      George Cukor           Sam Wood      Clark Gable     Vivien Leigh   
247       Clark Gable  Claudette Colbert  Walter Connolly     Roscoe Karns   
248  Maria Falconetti     Eugene Silvain     André Berley   Maurice Schutz   
249     Buster Keaton      Buster Keaton      Marion Mack    Glen Cavender   

       votes  metascore GROSS COLLECTION  
0     163431        NaN              NaN  
1    2515762       80.0          $28.34M  
2    1732749      100.0         $134.97M  
3    2466041       84.0         $534.86M  
4    1202401       90.0          $57.30M  
..       ...        ...              ...  
245   112642       73.0           $9.60M  
246   304725       97.0         $198.68M  
247   100198       87.0           $4.36M  
248    52264        NaN           $0.02M  
249    88022        NaN           $1.03M  

[250 rows x 16 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   ranking of movie    250 non-null    int64  
 1   movie name          250 non-null    object 
 2   Year                250 non-null    object 
 3   certificate         250 non-null    object 
 4   runtime             250 non-null    object 
 5   genre               250 non-null    object 
 6   RATING              250 non-null    float64
 7   DETAIL ABOUT MOVIE  250 non-null    object 
 8   DIRECTOR            250 non-null    object 
 9   ACTOR 1             250 non-null    object 
 10  ACTOR 2             250 non-null    object 
 11  ACTOR 3             250 non-null    object 
 12  ACTOR 4             250 non-null    object 
 13  votes               250 non-null    int64  
 14  metascore           218 non-null    float64
 15  GROSS COLLECTION    214 non-null    object 
dtypes: float

In [ ]:
df.describe()

ranking of movie      RATING         votes   metascore
count        250.000000  250.000000  2.500000e+02  218.000000
mean         125.500000    8.308400  5.785299e+05   82.449541
std           72.312977    0.234669  4.951304e+05   10.822392
min            1.000000    8.100000  2.653800e+04   55.000000
25%           63.250000    8.100000  1.688628e+05   75.000000
50%          125.500000    8.200000  4.313355e+05   84.000000
75%          187.750000    8.400000  8.854255e+05   90.000000
max          250.000000    9.400000  2.515762e+06  100.000000

In [ ]:
df.shape

(250, 16)

In [ ]:
df.isnull().sum()

ranking of movie       0
movie name             0
Year                   0
certificate            0
runtime                0
genre                  0
RATING                 0
DETAIL ABOUT MOVIE     0
DIRECTOR               0
ACTOR 1                0
ACTOR 2                0
ACTOR 3                0
ACTOR 4                0
votes                  0
metascore             32
GROSS COLLECTION      36
dtype: int64

In [ ]:
df.drop(["metascore"], axis=1)
df.drop(["GROSS COLLECTION"], axis=1)

ranking of movie                   movie name    Year certificate  \
0                   1                      Jai Bhim  -2021       TV-MA   
1                   2      The Shawshank Redemption  -1994           R   
2                   3                 The Godfather  -1972           R   
3                   4               The Dark Knight  -2008       PG-13   
4                   5        The Godfather: Part II  -1974           R   
..                ...                           ...    ...         ...   
245               246  Mr. Smith Goes to Washington  -1939      Passed   
246               247            Gone with the Wind  -1939      Passed   
247               248         It Happened One Night  -1934      Passed   
248               249    The Passion of Joan of Arc  -1928      Passed   
249               250                   The General  -1926      Passed   

     runtime                      genre  RATING  \
0    164 min               Crime, Drama     9.4   
1    142 min                      Drama     9.3   
2    175 min               Crime, Drama     9.2   
3    152 min       Action, Crime, Drama     9.0   
4    202 min               Crime, Drama     9.0   
..       ...                        ...     ...   
245  129 min              Comedy, Drama     8.1   
246  238 min    Drama, History, Romance     8.1   
247  105 min            Comedy, Romance     8.1   
248  114 min  Biography, Drama, History     8.1   
249   67 min  Action, Adventure, Comedy     8.1   

                                    DETAIL ABOUT MOVIE             DIRECTOR   \
0    When a tribal man is arrested for a case of al...         T.J. Gnanavel   
1    Two imprisoned men bond over a number of years...        Frank Darabont   
2    The Godfather follows Vito Corleone, Don of th...  Francis Ford Coppola   
3    When the menace known as the Joker wreaks havo...     Christopher Nolan   
4    The early life and career of Vito Corleone in ...  Francis Ford Coppola   
..                                                 ...                   ...   
245  A naive youth leader is appointed to fill a va...           Frank Capra   
246  The manipulative daughter of a Georgia plantat...        Victor Fleming   
247  A renegade reporter trailing a young runaway h...           Frank Capra   
248  In 1431, Jeanne d'Arc is placed on trial on ch...   Carl Theodor Dreyer   
249  After being rejected by the Confederate milita...        Clyde Bruckman   

              ACTOR 1            ACTOR 2          ACTOR 3          ACTOR 4  \
0              Suriya      Lijo Mol Jose       Manikandan  Rajisha Vijayan   
1         Tim Robbins     Morgan Freeman       Bob Gunton   William Sadler   
2       Marlon Brando          Al Pacino       James Caan     Diane Keaton   
3      Christian Bale       Heath Ledger    Aaron Eckhart    Michael Caine   
4           Al Pacino     Robert De Niro    Robert Duvall     Diane Keaton   
..                ...                ...              ...              ...   
245     James Stewart        Jean Arthur     Claude Rains    Edward Arnold   
246      George Cukor           Sam Wood      Clark Gable     Vivien Leigh   
247       Clark Gable  Claudette Colbert  Walter Connolly     Roscoe Karns   
248  Maria Falconetti     Eugene Silvain     André Berley   Maurice Schutz   
249     Buster Keaton      Buster Keaton      Marion Mack    Glen Cavender   

       votes  metascore  
0     163431        NaN  
1    2515762       80.0  
2    1732749      100.0  
3    2466041       84.0  
4    1202401       90.0  
..       ...        ...  
245   112642       73.0  
246   304725       97.0  
247   100198       87.0  
248    52264        NaN  
249    88022        NaN  

[250 rows x 15 columns]

In [ ]:
df.duplicated().sum()

0

In [ ]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_df = 0.3,
                            stop_words="english",
                            lowercase= True,
                            use_idf=True,
                            smooth_idf= True,
                            norm =u'l2')

In [ ]:
data = df["DETAIL ABOUT MOVIE"]
tfidf_matrix = vectorizer.fit_transform(data)

In [ ]:
vec = pd.DataFrame(tfidf_matrix[0].T.todense(), index = vectorizer.get_feature_names(), columns=['TF-IDF'])

vec = vec.sort_values('TF-IDF', ascending=False)

vec

TF-IDF
alleged     0.300187
rights      0.300187
arrested    0.300187
theft       0.300187
tribal      0.300187
...              ...
fellowship  0.000000
fellow      0.000000
feel        0.000000
federal     0.000000
zone        0.000000

[2165 rows x 1 columns]

In [ ]:
#Cosine_Similarity
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(tfidf_matrix,tfidf_matrix)
print(dict(sorted(similarity.items(), key=lambda item: item[1])))

AttributeError: 'numpy.ndarray' object has no attribute 'items'

In [ ]:
print(similarity)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
new_document = "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home."
new_document_tfidf = vectorizer.transform([new_document])
new_similarity = cosine_similarity(new_document_tfidf, tfidf_matrix)
  
print(new_similarity)

[[0.         0.         0.04147078 0.         0.03990816 0.
  0.06441884 0.06238645 0.         0.         0.         0.
  0.         0.         0.08103495 0.         0.         0.
  0.         0.         0.14209814 0.         0.         0.04077444
  0.         0.06325724 0.07156583 0.         0.         0.
  0.07902634 0.         0.         0.         0.         0.
  0.         0.         0.04988121 0.         0.         0.03637914
  0.         0.07334088 0.05492908 0.         0.         0.07994897
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.09306987 0.
  0.         0.03561686 0.         0.         0.         0.
  0.         0.05960433 0.         0.         0.         0.
  0.03908971 0.07379696 0.         0.         0.         0.
  0.         0.10710708 0.         0.         0.05966206 0.04651349
  0.         0.0518352  0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.    